<section id="about" class="about">
    <div class="group headshot">
        <header>
            <p class="s-s over-trigger">2.0</p>
        </header>
        <div class="tile over-trigger">
            <img alt="Profile Image" src="<?= $this->profile_img ?>">
            <div class="media-block">
                <h1 class="bold">Profile</h1>
            </div>
        </div>
    </div>
    <div class="group bio filled">
        <header>
            <p class="s-s">2.1</p>
        </header>
        <div class="content">
            <p>
                Hi, I'm Lawrence, a self-taught web developer currently based in Canterbury in the UK. I live and breathe HTML, CSS, and JavaScript, and love building fast, clean applications using the latest frameworks and tech stacks. From client-facing UI and Web APIs to server-side architecture and data storage, I'm on board for every step of the development process.
            </p>
            <button class="proficiencies hover-hl" aria-label="Toggle Proficiency List">
                <h2>
                    <span class="underline bold">
                        <span class="mode bold">See</span>&nbsp;Core Proficiencies</span>&nbsp;<span class="s-s arrow">&#9660;</span>
                </h2>
            </button>
            <section class="tech-list">
                <?php foreach ((array) $this->tech_lists as $tech_list): ?>
                    <div class="<?= $tech_list->id ?>">
                        <h2 class="bold">> <?= $tech_list->name ?></h2>
                        <ul class="tags">
                            <?php foreach((array) $tech_list->tags as $tag): ?>
                                <li><?= $tag ?></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endforeach; ?>
            </section>
            <p>
                When I’m not busy making things work, you can find me helping others out of programming jams, and adding new skills to my ever-expanding knowledge base. I’m also an occasionally-published poet and ever-aspiring musician, with a wide range of tastes that I constantly draw inspiration from. I’ll jump at any opportunity to let my creativity flow.
            </p>
        </div>
    </div>
    <div class="group links filled last">
        <header>
            <p class="s-s">2.2</p>
        </header>
        <ul>
            <?php foreach((array) $this->contact_links as $link): ?>
                <li><a class="hover-hl" href="<?= $link->href ?>" rel="noopener noreferrer" target="_blank">↳&nbsp;<span class="underline bold"><?= $link->name ?></span></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
</section>