<!DOCTYPE html>
<html lang="en" data-theme="<?= $this->theme ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script>window.MSInputMethodContext && document.documentMode && document.write('<script src="https://cdn.jsdelivr.net/gh/nuxodin/ie11CustomProperties@4.1.0/ie11CustomProperties.min.js"><\x2fscript>');</script>
    <script src="./dist/js/polyfills.js"></script>
    <script src="./dist/js/main.js"></script>
    <link rel="stylesheet" href="./dist/css/index.css">
    <link rel="stylesheet" href="./dist/css/splash.css">
    <?php foreach ((array) $this->page_styles as $style_src): ?>
        <link rel="stylesheet" href="<?= $style_src ?>">
    <?php endforeach; ?>
    <title>W.ITT <?= $this->page_tab ?></title>
</head>
<body>
    <div class="rulers">
        <div class="one">
            <div class="vr"></div>
        </div>
        <div class="two">
            <div class="vr"></div>
        </div>
    </div>
    <section class="splash">
        <div class="group title">
            <header>
                <p class="s-s">0.0</p>
            </header>
            <div>
                <a href="<?= BASE_URL ?>" class="hover-hl"><h1 class="bold">Lawrence Witt</h1></a>
                <h1><?= $this->page_title ?></h1>
            </div>
        </div>
        <div class="group subtitle">
            <header>
                <p class="s-s">0.1</p>
            </header>
            <div>
                <p>
                    <?= $this->page_desc ?>
                </p>
            </div>
        </div>
        <nav class="group nav last">
            <header>
                <p class="s-s">0.2</p>
            </header>
            <div class="content">
                <ul>
                    <li><a class="underline hover-hl" href="<?= BASE_URL ?>/#projects">projects</a></li>
                    <li><a class="underline hover-hl" href="<?= BASE_URL ?>/#about">about</a></li>
                </ul>
                <div class="theme-button-container">
                    <button class="theme" aria-label="Change Theme">
                        <svg class="sun" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M6.995 12c0 2.761 2.246 5.007 5.007 5.007s5.007-2.246 5.007-5.007-2.246-5.007-5.007-5.007S6.995 9.239 6.995 12zM11 19H13V22H11zM11 2H13V5H11zM2 11H5V13H2zM19 11H22V13H19z"/><path transform="rotate(-134.999 5.99 18.01)" d="M4.989 16.51H6.989V19.51H4.989z"/><path transform="rotate(-45.001 18.01 5.99)" d="M16.51 4.99H19.511000000000003V6.99H16.51z"/><path transform="rotate(-134.983 5.99 5.99)" d="M4.489 4.99H7.489V6.99H4.489z"/><path transform="rotate(134.999 18.01 18.01)" d="M17.01 16.51H19.01V19.511000000000003H17.01z"/></svg>
                        <svg class="moon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12,11.807C9.349,9.155,8.7,5.261,10.049,2c-1.875,0.37-3.666,1.281-5.12,2.735c-3.905,3.905-3.905,10.237,0,14.142	c3.906,3.906,10.237,3.905,14.143,0c1.454-1.454,2.364-3.244,2.735-5.119C18.545,15.106,14.651,14.458,12,11.807z"/></svg>
                    </button>
                </div>
            </div>
        </nav>
    </section>
    <?php foreach((array) $this->page_sections as $section): ?>
        <?= $section ?>
    <?php endforeach; ?>
    <?php foreach ((array) $this->page_scripts as $script_src): ?>
        <script src="<?= $script_src ?>"></script>
    <?php endforeach; ?>
</body>
</html>